[package]
name = "gridcore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
opt-level = 1
incremental = true

[profile.release]
incremental = true
lto = true
panic = "abort"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
reqwest = { version = "0.12.5", features = ["json"] }
jni = "0.21.1"
zip = "2.1.3"
log = "0.4.21"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
sha1 = "0.10.6"
fs-err = "2.11.0"
anyhow = "1.0.86"
